version: "3.2"

services:
  alice:
    container_name: alice
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    ports:
      - "9934:9934"
      - "9944:9944"
      - "30335:30335"
    command: bash -c "/polkadot --unsafe-ws-external --rpc-cors all --wasm-execution Compiled --rpc-external --rpc-methods Unsafe -d cumulus_relay/alice --validator --alice --ws-port 9944 --port 30335 --rpc-port 9934 --name alice --chain rococo-chachacha.json"
    volumes:
      - ./kylin_db/cumulus_relay:/cumulus_relay/
      - ./rococo-chachacha.json:/rococo-chachacha.json

  kylin-node:
    container_name: kylin-node
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    ports:
      - "9942:9942"
      - "9933:9933"
      - "30333:30333"
      - "30334:30334"
    command: bash -c "sleep 45;/kylin-node --unsafe-ws-external --rpc-cors all  --rpc-external --rpc-methods Unsafe -d cumulus_parachain/alice --collator --alice --force-authoring --ws-port 9942 --port 30333 --rpc-port 9933 --parachain-id 2013 -- --wasm-execution Compiled --port 30334 --chain rococo-chachacha.json"
    volumes:
      - ./kylin_db/cumulus_parachain:/cumulus_parachain/
      - ./rococo-chachacha.json:/rococo-chachacha.json
    depends_on:
      - alice

  bob:
    container_name: bob
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    ports:
      - "9935:9935"
      - "9955:9955"
      - "30336:30336"
    command: bash -c "sleep 45;/polkadot --unsafe-ws-external --rpc-cors all --wasm-execution Compiled --rpc-external --rpc-methods Unsafe -d cumulus_relay/bob --validator --bob --ws-port 9955 --port 30336 --rpc-port 9935 --name bob --chain rococo-chachacha.json"
    volumes:
      - ./kylin_db/cumulus_relay:/cumulus_relay/
      - ./rococo-chachacha.json:/rococo-chachacha.json
    depends_on:
      - alice

  charlie:
    container_name: charlie
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    ports:
      - "9936:9936"
      - "9956:9956"
      - "30337:30337"
    command: bash -c "sleep 30; /polkadot --unsafe-ws-external --rpc-cors all --wasm-execution Compiled --rpc-external --rpc-methods Unsafe -d cumulus_relay/charlie --validator --charlie --ws-port 9956 --port 30337 --rpc-port 9936 --name charlie --chain rococo-chachacha.json"
    depends_on:
      - bob
    volumes:
      - ./kylin_db/cumulus_relay:/cumulus_relay/
      - ./rococo-chachacha.json:/rococo-chachacha.json
      
  insert-ocw:
    container_name: insert-ocw
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    command: bash -c "sleep 600 && /insert_alice_key.sh"
    depends_on:
      - kylin-node

  kylin-market-frontend:
    container_name: kylin-market-frontend
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    ports:
      - "3001:3001"
    command: bash -c "cd /apps && serve -p 3001 build"
    depends_on:
      - kylin-node

  kylin-es:
    container_name: kylin-es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    environment:
      - discovery.type=single-node
    volumes:
      - es-data:/usr/share/elasticsearch/data

  kylin-kibana:
    container_name: kylin-kibana
    ports:
      - "5601:5601"
    image: docker.elastic.co/kibana/kibana:7.8.1
    environment:
      ELASTICSEARCH_HOSTS: http://kylin-es:9200
    depends_on:
      - kylin-es

  init-es-index:
    container_name: init-es-index
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 60 && /init_es_index.sh"
    depends_on:
      - kylin-es
      - kylin-kibana

  init-kibana-dashboard:
    container_name: init-kibana-dashboard
    image: kylinnetwork/kylin-node:polkadot-v0.9.7
    environment:
      ES_HOST: http://kylin-es:9200
      ES_INDEX_NAME: kylin_access_tracking
      KIBANA_HOST: http://kylin-kibana:5601
    command: /bin/bash -c "sleep 120 && /init_kibana_dashboard.sh"
    depends_on:
      - kylin-es
      - kylin-kibana
volumes:
  es-data:
    driver: local


